name = input("Enter patient name: ")
age = input("Enter patient age: ")
gender = input("Enter patient gender: ")
#print("Patient info: ", name, age, "years old", gender)
print("Patient info: " + name + " " + age + " years old " + " " + gender)
